
services:
  - type: web
    name: vernan-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://vernan-backend.onrender.com/api